---
title: "Log file"
author: "Larissa Voshol"
output:
  html_document:
    toc: true
    theme: united
---


# Preliminaries


# Introduction

## Goal

## Data collection

## Theory


# Experimental work

##15-05-2023

### Openen van data

Data is geopend.

```{r}

data_file <- "raw_data/Data_breath.csv"
data <- read.table(file = data_file,
                          header = TRUE,
                          sep = ",")
data

```
De data is prima, dataframe is zoals verwacht is.
Deze data ververvolgens op verschillende manieren geplot.

```{r}
library(ggplot2)
ggplot(data = data, aes(x = Sport , y = Peak_flow, colour = Sex)) + 
  geom_point()

```

##22-5-2023
Vervolg op het plotten van de data. Het verschil tussen peakflow voor en na 10 jumpingjacks.

```{r}

data <- data %>% group_by(Subject_id) %>% mutate(Diff_peak_flow = Peak_flow[2] - Peak_flow[1])

data %>%
  select(Sport) %>%
  mutate( sporting = case_when(Sport == c("Altheletiek", "Korfbal", "Sportschool", "Voetbal", "Volleybal", "Zwemmen") ~ "Yes", .default = "No"))

ggplot(data = data,
       mapping = aes(x = ))

```
